### ISSUE TITLE
composer.json wants to expose client/lang, which doesn't exist

### ISSUE THREAD

**Issue by nathancox** [firebrandhq/silverstripe-phonelink#1]
This is stopping composer from being able to install it.  It it supposed to point to just "lang"?

**Comment by marc-firebrand** [comment]
Thanks for the report, it was indeed an oversight from when we developed the module.
The lang folder actually doesn't need to be exposed at all.

We just pushed a fixed and released 2.0.1 (SS 4.2) / 1.0.2 (SS 4.0-4.1)
