### ISSUE TITLE
Can not add a phone number to existing content.

### ISSUE THREAD

**Issue by tedkrueger** [firebrandhq/silverstripe-phonelink#2]
I am not able to add a phone number link to content that is currently in an HTML field. I need to delete it, enter the content again, copy the phone number and add the link.

**Comment by antonsmithnz** [comment]
I've had no luck replicating this issue, it seems to work for me?

I'm wondering if a screen capture as a GIF might help here? Also which browser/version are you using?

**Comment by tedkrueger** [comment]
This may have been fixed in the last version update. I'm not seeing it either. Thanks for the response though.

**Comment by antonsmithnz** [comment]
Okay, I'll close this for now but it it happens again feel free to let us know.

**Comment by tedkrueger** [comment]
Definitely. Thanks again.
