### ISSUE TITLE
Edit link modal will not close

### ISSUE THREAD

**Issue by tedkrueger** [firebrandhq/silverstripe-phonelink#3]
After clicking edit link when a phone number link has been added, the modal fires. The only way to close it for me is to select the insert link button. Clicking the X will not close the modal.

**Comment by antonsmithnz** [comment]
What version of SS and the module are you using?

**Comment by tedkrueger** [comment]
Sorry for not adding it above. 
Composer.json
`"firebrandhq/silverstripe-phonelink": "^2.0",`
`"silverstripe/recipe-cms": "4.2.2@stable",`

**Comment by antonsmithnz** [comment]
Thanks for the report, this is now fixed with release `2.0.2`.

**Comment by tedkrueger** [comment]
Thanks.
